class Team {
  final int id;
  final String name;
  late int played;
  late int goals;
  late int code;
  late int fouls;
  late int points;
  late int W;
  late int D;
  late int L;

  Team({
    required this.id,
    required this.code,
    required this.name,
    required this.played,
    required this.goals,
    required this.fouls,
    required this.points,
    required this.W,
    required this.D,
    required this.L,
  });

  @override
  String toString() {
    return '{id : $id ,code : $code ,name: $name, played: $played, goals: $goals, fouls: $fouls, points: $points , W: $W ,L: $L ,D: $D}';
  }
}

var listandings = [
  {
    'id': 1,
    'code': 1,
    'name': 'Manchester United',
    'played': 0,
    'goals': 0,
    'fouls': 0,
    'points': 0,
    'W': 0,
    'L': 0,
    'D': 0,
  },
  {
    'id': 2,
    'code': 2,
    'name': 'Manchester City',
    'played': 0,
    'goals': 0,
    'fouls': 0,
    'points': 0,
    'W': 0,
    'L': 0,
    'D': 0,
  },
  {
    'id': 3,
    'code': 3,
    'name': 'AC Milan',
    'played': 0,
    'goals': 0,
    'fouls': 0,
    'points': 0,
    'W': 0,
    'L': 0,
    'D': 0,
  },
  {
    'id': 4,
    'code': 4,
    'name': 'Inter Milan',
    'played': 0,
    'goals': 0,
    'fouls': 0,
    'points': 0,
    'W': 0,
    'L': 0,
    'D': 0,
  },
  {
    'id': 5,
    'code': 5,
    'name': 'FC Barcelona',
    'played': 0,
    'goals': 0,
    'fouls': 0,
    'points': 0,
    'W': 0,
    'L': 0,
    'D': 0,
  },
  {
    'id': 6,
    'code': 6,
    'name': 'Real Madrid',
    'played': 0,
    'goals': 0,
    'fouls': 0,
    'points': 0,
    'W': 0,
    'L': 0,
    'D': 0,
  },
  {
    'id': 7,
    'code': 7,
    'name': 'Arsenal FC',
    'played': 0,
    'goals': 0,
    'fouls': 0,
    'points': 0,
    'W': 0,
    'L': 0,
    'D': 0,
  },
  {
    'id': 8,
    'code': 8,
    'name': 'Tottenham Hotspurs',
    'played': 0,
    'goals': 0,
    'fouls': 0,
    'points': 0,
    'W': 0,
    'L': 0,
    'D': 0,
  },
  {
    'id': 9,
    'code': 9,
    'name': 'Bayern Munchen',
    'played': 0,
    'goals': 0,
    'fouls': 0,
    'points': 0,
    'W': 0,
    'L': 0,
    'D': 0,
  },
  {
    'id': 10,
    'code': 10,
    'name': 'Ajax FC',
    'played': 0,
    'goals': 0,
    'fouls': 0,
    'points': 0,
    'W': 0,
    'L': 0,
    'D': 0,
  },
  {
    'id': 11,
    'code': 11,
    'name': 'Atletico Madrid',
    'played': 0,
    'goals': 0,
    'fouls': 0,
    'points': 0,
    'W': 0,
    'L': 0,
    'D': 0,
  },
  {
    'id': 12,
    'code': 12,
    'name': 'Chelsea',
    'played': 0,
    'goals': 0,
    'fouls': 0,
    'points': 0,
    'W': 0,
    'L': 0,
    'D': 0,
  },
  {
    'id': 13,
    'code': 13,
    'name': 'Dortmund',
    'played': 0,
    'goals': 0,
    'fouls': 0,
    'points': 0,
    'W': 0,
    'L': 0,
    'D': 0,
  },
  {
    'id': 14,
    'code': 14,
    'name': 'PSG',
    'played': 0,
    'goals': 0,
    'fouls': 0,
    'points': 0,
    'W': 0,
    'L': 0,
    'D': 0,
  },
  {
    'id': 15,
    'code': 15,
    'name': 'Juventus',
    'played': 0,
    'goals': 0,
    'fouls': 0,
    'points': 0,
    'W': 0,
    'L': 0,
    'D': 0,
  },
  {
    'id': 16,
    'code': 16,
    'name': 'Napoli',
    'played': 0,
    'goals': 0,
    'fouls': 0,
    'points': 0,
    'W': 0,
    'L': 0,
    'D': 0,
  },
  {
    'id': 17,
    'code': 17,
    'name': 'Porto',
    'played': 0,
    'goals': 0,
    'fouls': 0,
    'points': 0,
    'W': 0,
    'L': 0,
    'D': 0,
  },
  {
    'id': 18,
    'code': 18,
    'name': 'Rangers',
    'played': 0,
    'goals': 0,
    'fouls': 0,
    'points': 0,
    'W': 0,
    'L': 0,
    'D': 0,
  },
  {
    'id': 19,
    'code': 19,
    'name': 'Sporting',
    'played': 0,
    'goals': 0,
    'fouls': 0,
    'points': 0,
    'W': 0,
    'L': 0,
    'D': 0,
  },
  {
    'id': 20,
    'code': 20,
    'name': 'Sevilla',
    'played': 0,
    'goals': 0,
    'fouls': 0,
    'points': 0,
    'W': 0,
    'L': 0,
    'D': 0,
  },
];
